# Generated by Django 3.2 on 2022-06-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=188, unique=True)),
                ('password', models.CharField(max_length=188)),
                ('initial_balance', models.FloatField(default=500000)),
                ('cows', models.IntegerField(default=5)),
                ('goats', models.IntegerField(default=5)),
                ('sheeps', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStockPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalePurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cows', models.IntegerField(default=0)),
                ('goats', models.IntegerField(default=0)),
                ('sheeps', models.IntegerField(default=0)),
                ('customer_farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to='farmers.farmers')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.farmers')),
                ('seller_farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Seller', to='farmers.farmers')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockOnMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cows', models.IntegerField(default=0)),
                ('goats', models.IntegerField(default=0)),
                ('sheeps', models.IntegerField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.farmers')),
            ],
        ),
    ]
