# Generated by Django 3.2 on 2022-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepurchasehistory',
            name='customer_farmer',
        ),
        migrations.RemoveField(
            model_name='salepurchasehistory',
            name='seller_farmer',
        ),
        migrations.AddField(
            model_name='salepurchasehistory',
            name='customer_farmer_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='salepurchasehistory',
            name='seller_farmer_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='salepurchasehistory',
            name='market_id',
            field=models.IntegerField(default=False),
        ),
    ]
