# Generated by Django 3.2 on 2022-06-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20220612_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStockPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='farmers',
            name='cows',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='goats',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='initial_balance',
            field=models.FloatField(default=500000),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='sheeps',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='LivestockOnMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cows', models.IntegerField(default=0)),
                ('goats', models.IntegerField(default=0)),
                ('sheeps', models.IntegerField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.farmers')),
            ],
        ),
    ]
